name = "consenstat"
main = "src/worker/index.ts"
compatibility_date = "2026-03-08"

[assets]
directory = "./dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "consenstat"
database_id = "46c43899-821a-4582-8f43-aeb1e8ee4b26"

[[durable_objects.bindings]]
name = "EXAM_ROOMS"
class_name = "ExamRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ExamRoom"]
